src/SAM/PortfolioBundle/Entity/Project.php
<?php

namespace SAM\PortfolioBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use SAM\PortfolioBundle\Entity\Image;
use SAM\PortfolioBundle\Entity\Technology;


/**
 * Project
 *
 * @ORM\Table(name="project")
 * @ORM\Entity(repositoryClass="SAM\PortfolioBundle\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, unique=true)
     */
    private $url;

    /**
     * @ORM\ManyToMany(targetEntity="SAM\PortfolioBundle\Entity\Image", cascade={"persist", "remove"})
     *  @ORM\JoinTable(name="sam_images")
     */
    private $images;

    /**
     * @ORM\ManyToMany(targetEntity="SAM\PortfolioBundle\Entity\Technology", cascade={"persist"})
     * @ORM\JoinTable(name="sam_technology")
     */
    private $technologies;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->technologies = new ArrayCollection();
        $this->images = new ArrayCollection();
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Project
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Project
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Project
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Add images
     *
     * @param Image $images
     *
     * @return Project
     */
    public function addImage(Image $images)
    {
        $this->images[] = $images;

        return $this;
    }

    /**
     * Remove images
     *
     * @param Image $images
     */
    public function removeImage(Image $images)
    {
        $this->images->removeElement($images);
    }

    /**
     * Get images
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getImage()
    {
        return $this->images;
    }

    /**
     * Add technology
     *
     * @param Technology $technology
     *
     * @return Project
     */
    public function addTechnology(Technology $technology)
    {
        $this->technologies[] = $technology;

        return $this;
    }

    /**
     * Remove technology
     *
     * @param Technology $technology
     */
    public function removeTechnology(Technology $technology)
    {
        $this->technologies->removeElement($technology);
    }

    /**
     * Get technologies
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTechnologies()
    {
        return $this->technologies;
    }


    /**
     * @return string
     * For Twig view
     */
    public function getWebPath()
    {
        return __DIR__.'/../../../../web/uploads/img';
    }
}

src/SAM/PortfolioBundle/Resources/views/Core/portfolio.html.twig
{% extends "SAMCoreBundle::layout.html.twig" %}

{% block body %}
    <h1 class="text-center">{{ 'portfolio.title'|trans }}</h1>
    <section class="container" id="project">
        <div class="row">
            {% for project in projects %}
                <div class="col-lg-6 p-3 hovereffect {{ project.name |lower }} border border-white">
                    <div class="overlay">
                        <h2 class="col-lg-12 text-center">{{ project.name |upper }}</h2>
                        <p class="col-lg-12">{{ project.description }}</p>
                        <article class="view-project">
                            {% for img in project.image.values %}
                                {% if loop.index is odd %}
                                    <div>
                                        <img class="image{{ loop.index }} col-lg-12" src="{{ asset('bundles/../uploads/img')}}/{{ img.alt }}" alt="{{ img.alt }}">
                                        <a class="info text-warning" href="{{ project.url }}" target="_blank">{{ 'portfolio.redirect'|trans }}</a>
                                    </div>
                                {% endif %}
                                {% if loop.index is even %}
                                    <h4 class="col-lg-12">{{ 'portfolio.details'|trans }}</h4>
                                    <nav class="d-flex">
                                        <div class="col-lg-9">
                                            {% for tech in project.technologies.values %}
                                                <span class="badge badge-info p-2">{{ tech.name }}</span>
                                            {% endfor %}
                                        </div>
                                        <button type="button"
                                                class="btn btn-primary d-none d-lg-block"
                                                title="{{ project.name }}"
                                                data-trigger="focus"
                                                data-content="
                                        <div class='media'>
                                                <img style='width: 100%;' src='{{ asset('bundles/../uploads/img')}}/{{ img.alt }}'
                                                class='media-object' alt='Sample Image'>
                                        </div>"
                                                data-toggle="popover">{{ 'portfolio.look'|trans }}
                                        </button>
                                    </nav>
                                {% endif %}
                            {% endfor %}
                        </article>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    <hr>
    <section class="container" id="certifications">
        <h1 class="text-center">{{ 'portfolio.certificat'|trans }}</h1>
        <div class="donut">
            {% if (app.request.getLocale()) == 'fr' %}
            <canvas id="myChartFr" class="w-75 h-50" ></canvas>
            {% elseif (app.request.getLocale()) == 'en' %}
            <canvas id="myChartEn" class="w-75 h-50" ></canvas>
            {% endif %}
        </div>
        <br>
        <h2>{{ 'portfolio.total'|trans }}: {{ certifications | length }}</h2>
        <article id="zoneCertif" class="row">
            {% if listweb %}
            <section id="webCertif" class="col-lg-5">
                <h4 class="text-center">{{ 'portfolio.webGen'|trans }}</h4>
                {% for web in listweb %}
                    <a class="allweb {{ web.certifNumber }}" href="{{ asset('bundles/../uploads/img')}}/{{ web.image.alt }}">
                        {{ web.title }}
                    </a>
                    <br>
                {% endfor %}
            </section>
            {% endif %}
            {% if listhtml %}
                <section id="htmlCertif" class="col-lg-5">
                    <h4 class="text-center">HTML5/CSS3</h4>
                    {% for html in listhtml %}
                        <a class="allhtml {{ html.certifNumber }}" href="{{ asset('bundles/../uploads/img')}}/{{ html.image.alt }}">
                            {{ html.title }}
                        </a>
                        <br>
                    {% endfor %}
                </section>
            {% endif %}
            {% if listjs %}
            <section id="jsCertif" class="col-lg-5">
                <h4 class="text-center">Javascript</h4>
                {% for js in listjs %}
                    <a class="alljs {{ js.certifNumber}}" href="{{ asset('bundles/../uploads/img')}}/{{ js.image.alt }}">
                        {{ js.title }}
                    </a>
                    <br>
                {% endfor %}
            </section>
            {% endif %}
            {% if listphp %}
                <section id="phpCertif" class="col-lg-5">
                    <h4 class="text-center">PHP</h4>
                    {% for php in listphp %}
                        <a class="allphp {{ php.certifNumber }}" href="{{ asset('bundles/../uploads/img')}}/{{ php.image.alt }}">
                            {{ php.title }}
                        </a>
                        <br>
                    {% endfor %}
                </section>
            {% endif %}
        </article>
    </section>
{% endblock %}


{% block js %}
    {% javascripts '@SAMCoreBundle/Resources/public/js/donuts.js' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
    {% javascripts '@SAMCoreBundle/Resources/public/js/pop.js' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}